fix(ci): Multi-platform build is not supported for the docker driver. (#5)
* Fix release version

* fix(ci): Adds support ot QEMU

Fix errors:

```
ERROR: Multi-platform build is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https://docs.docker.com/go/build-multi-platform/
Error: buildx failed with: Learn more at https://docs.docker.com/go/build-multi-platform/
```

* feat(ci): Add support to dockerhub

diff --git a/.github/workflows/generate-package.yaml b/.github/workflows/generate-package.yaml
--- a/.github/workflows/generate-package.yaml
+++ b/.github/workflows/generate-package.yaml
@@ -11,7 +11,8 @@ on:
         required: true
 
 jobs:
-  build-and-push-docker-image:
+  build-and-push-docker-image-to-ghcr:
+    name: "Build package to Github Container Registry"
     runs-on: ubuntu-latest
     permissions:
       contents: read
@@ -20,6 +21,13 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v2
 
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v2
@@ -61,4 +69,59 @@ jobs:
         uses: docker/build-push-action@v3
         with:
           context: .
+          push: true
+
+  # Dockerhub
+  build-and-push-docker-image-to-dockerhub:
+    name: "Build package to Dockerhub"
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      packages: write
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          registry: docker.io # Or registry: https://index.docker.io/v1/
+          username: ${{ vars.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Extract release tag
+        id: extract_release_tag
+        run: |
+
+          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
+            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
+          elif [[ -n "${{ github.event.release.tag_name }}" ]]; then
+            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
+          else
+            echo "::error title=Tag not found::No tag found in either github.event.inputs.tag or github.event.release.tag_name"
+            exit 1 # Exit with error if no tag is found
+          fi
+
+      - name: Build and tag Docker image with release version
+        uses: docker/build-push-action@v3
+        with:
+          context: .
+          platforms: linux/amd64,linux/arm64
+          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.extract_release_tag.outputs.tag }}
+          push: true
+
+      - name: Build and tag Docker image with 'latest' tag
+        uses: docker/build-push-action@v3
+        with:
+          context: .
+          platforms: linux/amd64,linux/arm64
+          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest
           push: true
